name: Testes React

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test -- --watchAll=false

      - name: Notificar Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"📢 CI rodou - Status: ${{ job.status }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}