name: Testes React
  /*
    Este workflow é acionado em pushes e pull requests para a branch master.
    Ele executa os testes do projeto React e, independentemente do resultado, envia uma notificação para um canal do Discord.
  */
on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test -- --watchAll=false
          
         // teste 
      - name: Notificar Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\":\"📢 CI Finalizado | Status: ${{ job.status }} | Autor: ${{ github.actor }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}